# Generated by Django 3.1.14 on 2022-08-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220810_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='avatar',
            field=models.ImageField(default='run/media_root/default_user.png', upload_to='uploads/'),
        ),
    ]
